import creature, grid

g = grid.Grid(9, 9)
c = g.set_cell(6, 0, None)
print(c)
f = creature.Fish(c, 5)
g.set_cell(6, 0, f)
print(c)
c.remove_creature()
print(c)

# Cell::get_neighbors() and Grid::set_cell()
print(c.get_neighbors())
print(g.get_neighbors(6, 0))
g.set_cell(5, 0, " fIsh")
g.set_cell(7, 0, creature.Shark(g.get_cell(7, 0), 8))
print(g.get_neighbors(6, 0))

# Creature::die()
s2 = creature.Shark(g.get_cell(6, 1), 5, 5)
g.set_cell(6, 1, s2)
print(g)
print(g.get_neighbors(7, 1))
s2.die()
print(g.get_neighbors(7, 1))

# Fish::move()
f2 = creature.Fish(g.get_cell(3, 2), 2)
g.set_cell(3, 2, f2)
g.set_cell(3, 1, "shark")
print(g.get_neighbors(3, 2))
print(g)
f2.move()
print(g.get_neighbors(3, 2))
print(g)
